In [ ]:
# Q2 II. (a)

In [2]:
import numpy as np

def matrix_sum(A, B):
    return np.add(A, B)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = matrix_sum(A, B)

print("Matrix A:")
print(A)


print("\nMatrix B:")
print(B)

print("\nA + B =")
print(result)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A + B =
[[ 6  8]
 [10 12]]


In [3]:
# Q2 II. (b)

In [4]:
import numpy as np

def matrix_determinant(matrix):
    return np.linalg.det(matrix)
    
A = np.array([[4, 2], [3, 1]])

det = matrix_determinant(A)

print("Matrix A:")
print(A)

print("\nDeterminant of A =", det)


Matrix A:
[[4 2]
 [3 1]]

Determinant of A = -2.0


In [5]:
# Q2 II. (c)

In [6]:
import numpy as np

def matrix_transpose(A):
    return A.T
    
A = np.array([[1, 2, 3], [4, 5, 6]])

transpose = matrix_transpose(A)

print("Matrix A:")
print(A)

print("\nTranspose of A:")
print(transpose)
# print(A.T)



Matrix A:
[[1 2 3]
 [4 5 6]]

Transpose of A:
[[1 4]
 [2 5]
 [3 6]]


In [7]:
# Q2 II. (d)

In [8]:
import numpy as np

def is_symmetric(A):
    return np.array_equal(A, A.T)

A = np.array([[1, 2, 3],
              [2, 5, 6],
              [3, 6, 9]])

print("Matrix A:")
print(A)

if is_symmetric(A):
    print("\nMatrix A is symmetric.")
else:
    print("\nMatrix A is not symmetric.")


Matrix A:
[[1 2 3]
 [2 5 6]
 [3 6 9]]

Matrix A is symmetric.


In [9]:
# Q2 II. (e)

In [10]:
import numpy as np

def multiply_matrices(A, B):
    if A.shape[1] != B.shape[0]:
        print("Cannot multiply: Columns of A must equal rows of B.")
        return None
    else:
        return np.dot(A, B)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = multiply_matrices(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

if result is not None:
    print("\nA × B =")
    print(result)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A × B =
[[19 22]
 [43 50]]


In [11]:
# Q2 III. (a)

In [12]:
import numpy as np

def multiply_matrices(X, X1):
    if X.shape[1] != X1.shape[0]:
        print("Cannot multiply: Columns of A must equal rows of B.")
        return None
    else:
        return np.dot(X, X1)
a=np.cos(np.pi/6)
b=np.sin(np.pi/6)

X = np.array([[a], [b]])
Y = np.array([[b], [-a]])
X1=X.T
Y1=Y.T
result = multiply_matrices(X, X1)

print("Matrix X:")
print(X)

print("\nMatrix Y:")
print(Y)

if result is not None:
    print("\nX × X^T =")
    print(result)

def multiply_matrices(Y, Y1):
    if Y.shape[1] != Y1.shape[0]:
        print("Cannot multiply: Columns of A must equal rows of B.")
        return None
    else:
        return np.dot(Y, Y1)
result1 = multiply_matrices(Y, Y1)
if result is not None:
    print("\nY× Y^T =")
    print(result1)
A=result + result1

print("\n The A answer is :" ,A)




Matrix X:
[[0.8660254]
 [0.5      ]]

Matrix Y:
[[ 0.5      ]
 [-0.8660254]]

X × X^T =
[[0.75      0.4330127]
 [0.4330127 0.25     ]]

Y× Y^T =
[[ 0.25      -0.4330127]
 [-0.4330127  0.75     ]]

 The A answer is : [[1. 0.]
 [0. 1.]]


In [13]:
# Q2 III. (b)

In [14]:
import numpy as np

def is_symmetric(A):
    return np.array_equal(A, A.T)

A = np.array([[2, 1, -3],
              [1, 2, -3],
              [-3, -3, -3]])

print("Matrix A:")
print(A)

if is_symmetric(A):
    print("\nMatrix A is symmetric.")
else:
    print("\nMatrix A is not symmetric.")


Matrix A:
[[ 2  1 -3]
 [ 1  2 -3]
 [-3 -3 -3]]

Matrix A is symmetric.


In [15]:
# Q2 III. (c)

In [16]:
import numpy as np
pi=np.pi
A=pi/3
B=pi/4
D=pi/4
G=3*pi/2
a=np.cos(G/2)
b=np.sin(G/2)


def cexp(theta):
    return np.cos(theta) + 1j*np.sin(theta)
    
M1=np.array([[cexp(-B/2), 0], [0, cexp(B/2)]])
M2=np.array([[a, -b], [b, a]])
M3=np.array([[cexp(-G/2), 0], [0, cexp(-G/2)]])

k=cexp(A)
U=A*M1@M2@M3
print (U)


[[ 0.68411477+0.28336962j  0.68411477+0.28336962j]
 [-0.28336962-0.68411477j  0.28336962+0.68411477j]]
